### ISSUE TITLE
Unsorted Merge doesn't exist in iterlib-python

### ISSUE THREAD

**Issue by adsharma** [facebookincubator/iterlib#29]
Test case:

```
./mock.py "(or (assoc 100 (3 2 1)) (assoc 200 (3 2 1)))" -t
Traceback (most recent call last):
  File "./mock.py", line 56, in <module>
    tree = test_execute_hier(query[0])
  File "./mock.py", line 44, in test_execute_hier
    visitor.visit(e['query'])
  File "/home/asharma/src/iterlib/python/visitor.py", line 38, in visit
    meth(node)
  File "/home/asharma/src/iterlib/python/execute.py", line 256, in visit_or
    self.iter = union(iters)
  File "/home/asharma/src/iterlib/python/execute.py", line 71, in union
    return iter([k for k, g in itertools.groupby(source, project_item([":id"]))])
  File "/home/asharma/src/iterlib/python/execute.py", line 71, in <listcomp>
    return iter([k for k, g in itertools.groupby(source, project_item([":id"]))])
  File "/usr/local/fbcode/gcc-4.8.1-glibc-2.17-fb/lib/python3.5/heapq.py", line 353, in merge
    _heapify(h)
TypeError: unorderable types: dict() < dict()
```

**Comment by adsharma** [comment]
`or` operator tries to do a sorted merge, which isn't always possible.
`merge` operator, which does unsorted merge is the right solution to the problem.
